{
 "title": " Custom Exporter ",
 "time": { "from": "2025-11-03T04:56:07.706Z", "to": "2025-11-03T16:56:07.706Z" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "Сity",
    "query": {
     "query": "label_values(weather_temperature_celsius, city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Средняя влажность по городам",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(weather_windspeed_kmh{city=\"$city\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сумма осадков",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(weather_temperature_celsius{city=~\"$city\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Минимальное давление за последние 50 минут",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "min_over_time(weather_pressure_hpa{city=~\"$city\"}[50m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальная скорость ветра за последние 50 минут",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(weather_windspeed_kmh{city=~\"$city\"}[50m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Разница между температурой и скоростью ветра",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=~\"$city\"} - (weather_windspeed_kmh{city=~\"$city\"} / 10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя температура группами по стране",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "avg by (country) (weather_temperature_celsius{city=~\"$city\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "активность по температуре",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius{city=\"$city\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя скорость ветра по градусу направления",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "avg by (winddirection) (weather_windspeed_kmh{city=~\"$city\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальная скорость ветра",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(weather_windspeed_kmh{city=~\"$city\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя температура за 5 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius{city=~\"$city\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}